//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fx.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer size must be large enough to hold &apos;count&apos; bytes at &apos;offset&apos;; count: &apos;{0}&apos;; offset: &apos;{1}&apos;; buffer length: &apos;{2}&apos;.
        /// </summary>
        internal static string ChunkedMemoryStreamRead {
            get {
                return ResourceManager.GetString("ChunkedMemoryStreamRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This stream does not support writing.
        /// </summary>
        internal static string ChunkedMemoryStreamSetLength {
            get {
                return ResourceManager.GetString("ChunkedMemoryStreamSetLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer size must be large enough to hold &apos;count&apos; bytes at &apos;offset&apos;; count: &apos;{0}&apos;; offset: &apos;{1}&apos;; buffer length: &apos;{2}&apos;.
        /// </summary>
        internal static string ChunkedMemoryStreamWriteSize {
            get {
                return ResourceManager.GetString("ChunkedMemoryStreamWriteSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This stream does not support writing.
        /// </summary>
        internal static string ChunkedMemoryStreamWriteSupport {
            get {
                return ResourceManager.GetString("ChunkedMemoryStreamWriteSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; did not contain any elements.
        /// </summary>
        internal static string EnsureEnumerableNotEmpty {
            get {
                return ResourceManager.GetString("EnsureEnumerableNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; was not a valid value of the enumeration &apos;{1}&apos;.
        /// </summary>
        internal static string EnsureIsDefinedEnum {
            get {
                return ResourceManager.GetString("EnsureIsDefinedEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid enumeration type.
        /// </summary>
        internal static string EnsureIsEnum {
            get {
                return ResourceManager.GetString("EnsureIsEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is of type &apos;{1}&apos; which is not derived from &apos;{2}&apos;.
        /// </summary>
        internal static string EnsureIsInstance {
            get {
                return ResourceManager.GetString("EnsureIsInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; was not a positive value.
        /// </summary>
        internal static string EnsureIsPositive {
            get {
                return ResourceManager.GetString("EnsureIsPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid MAC address; provided value: &apos;{1}&apos;; expected format: &apos;{2}&apos;.
        /// </summary>
        internal static string EnsureIsValidMacAddress {
            get {
                return ResourceManager.GetString("EnsureIsValidMacAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid SHA1; provided value: &apos;{1}&apos;; expected format: &apos;{2}&apos;.
        /// </summary>
        internal static string EnsureIsValidSha1 {
            get {
                return ResourceManager.GetString("EnsureIsValidSha1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid SHA1 or SHA2; provided value: &apos;{1}&apos;; expected formats: &apos;{2}&apos; &apos;{3}&apos;.
        /// </summary>
        internal static string EnsureIsValidSha1OrSha2 {
            get {
                return ResourceManager.GetString("EnsureIsValidSha1OrSha2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid SHA2; provided value: &apos;{1}&apos;; expected format: &apos;{2}&apos;.
        /// </summary>
        internal static string EnsureIsValidSha2 {
            get {
                return ResourceManager.GetString("EnsureIsValidSha2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; was a negative value.
        /// </summary>
        internal static string EnsureNotNegative {
            get {
                return ResourceManager.GetString("EnsureNotNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be the empty string.
        /// </summary>
        internal static string EnsureNotNullOrEmptyString {
            get {
                return ResourceManager.GetString("EnsureNotNullOrEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were an unequal number of left and right curly braces in the provided format.
        /// </summary>
        internal static string EventIdentifierExtensionsFormat {
            get {
                return ResourceManager.GetString("EventIdentifierExtensionsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred generating this event. The message format was: {0}. The data was: {1}.
        /// </summary>
        internal static string LoggerExtensionsFormat {
            get {
                return ResourceManager.GetString("LoggerExtensionsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred generating this event. The message format was: {0}. The data was: {1}.
        /// </summary>
        internal static string MemoryTraceListenerTraceEvent {
            get {
                return ResourceManager.GetString("MemoryTraceListenerTraceEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during deserialization.
        /// </summary>
        internal static string WcfSerializerDeserialization {
            get {
                return ResourceManager.GetString("WcfSerializerDeserialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during serialization.
        /// </summary>
        internal static string WcfSerializerSerialization {
            get {
                return ResourceManager.GetString("WcfSerializerSerialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during deserialization.
        /// </summary>
        internal static string XmlSerializerDeserialization {
            get {
                return ResourceManager.GetString("XmlSerializerDeserialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during serialization.
        /// </summary>
        internal static string XmlSerializerSerialization {
            get {
                return ResourceManager.GetString("XmlSerializerSerialization", resourceCulture);
            }
        }
    }
}
